import type { Product } from "@/lib/reco/types";

/**
 * supabase/seed.sql과 1:1로 대응하는 시드 상품 10개.
 * 용도: (1) Supabase 미설정 시 개발 폴백 (2) 추천 엔진 테스트 픽스처.
 * seed.sql을 수정하면 이 파일도 함께 수정할 것.
 */

const base = {
  image_url: null as string | null,
  installation_service: "none" as const,
  installation_fee: null as number | null,
  mattress_included: false,
  scheduled_delivery: false,
  bed_size: "SS",
  under_bed_clearance_cm: null as number | null,
  has_outlet: false,
  has_headboard: false,
  carry_service_available: false,
  assembly_service_available: false,
  assembly_people: 1,
  disassembly_ease: "medium" as const,
  data_confidence: "confirmed" as const,
  status: "public" as const,
  created_at: "2026-07-01T00:00:00Z",
  updated_at: "2026-07-01T00:00:00Z",
};

export const SEED_PRODUCTS: Product[] = [
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000001",
    name: "루미 슈퍼싱글 서랍 수납침대",
    seller_name: "오늘의가구",
    seller_url: "https://example.com/lumi-ss-drawer",
    price: 159000,
    shipping_fee: 30000,
    mattress_price: 89000,
    delivery_days_min: 5,
    delivery_days_max: 7,
    width_cm: 115,
    length_cm: 205,
    height_cm: 32,
    material: "PB+LPM",
    storage_type: "drawer",
    colors: ["화이트", "오크"],
    storage_capacity: "medium",
    dust_blocking: "high",
    cleaning_ease: "easy",
    robot_vacuum_fit: "no",
    carry_difficulty: "medium",
    self_assembly: "medium",
    assembly_people: 2,
    assembly_tools: "십자드라이버 필요(미동봉)",
    review_risks: ["assembly_hard"],
    recommended_for: "자잘한 짐이 많은 자취생",
    not_recommended_for: "이사가 잦거나 혼자 조립이 어려운 사람",
    source_note: "공식몰 상세페이지",
    last_verified_at: "2026-07-08",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000002",
    name: "스텔라 LED 리프트업 수납침대",
    seller_name: "한샘몰",
    seller_url: "https://example.com/stella-liftup",
    price: 299000,
    shipping_fee: 0,
    installation_service: "included",
    mattress_price: 120000,
    delivery_days_min: 14,
    delivery_days_max: 21,
    scheduled_delivery: true,
    width_cm: 118,
    length_cm: 208,
    height_cm: 95,
    material: "PB+친환경 E0",
    storage_type: "lift_up",
    has_outlet: true,
    has_headboard: true,
    colors: ["화이트", "그레이"],
    storage_capacity: "large",
    dust_blocking: "high",
    cleaning_ease: "easy",
    robot_vacuum_fit: "no",
    carry_difficulty: "hard",
    carry_service_available: true,
    self_assembly: "not_possible",
    assembly_service_available: true,
    assembly_people: 2,
    assembly_tools: "전문 기사 설치",
    disassembly_ease: "hard",
    review_risks: ["smell"],
    recommended_for: "겨울 이불처럼 큰 짐을 통째로 넣고 싶은 사람",
    not_recommended_for: "2년 안에 이사할 가능성이 높은 사람",
    source_note: "공식몰 상세페이지",
    last_verified_at: "2026-07-05",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000003",
    name: "코지 원목 슈퍼싱글 침대 (하부 25cm)",
    seller_name: "코지홈 스토어",
    seller_url: "https://example.com/cozy-wood",
    price: 129000,
    shipping_fee: 25000,
    mattress_price: 95000,
    delivery_days_min: 3,
    delivery_days_max: 5,
    width_cm: 112,
    length_cm: 203,
    height_cm: 28,
    material: "고무나무 원목",
    storage_type: "legs_open",
    under_bed_clearance_cm: 25,
    colors: ["내추럴"],
    storage_capacity: "small",
    dust_blocking: "low",
    cleaning_ease: "easy",
    robot_vacuum_fit: "ok",
    carry_difficulty: "easy",
    self_assembly: "easy",
    assembly_tools: "육각렌치 동봉",
    disassembly_ease: "easy",
    review_risks: ["wobble"],
    recommended_for: "로봇청소기를 쓰는 자취생",
    not_recommended_for: "수납 공간이 많이 필요한 사람",
    source_note: "공식 스마트스토어",
    last_verified_at: "2026-07-09",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000004",
    name: "브리즈 스틸 프레임 슈퍼싱글",
    seller_name: "쿠팡",
    seller_url: "https://example.com/breeze-steel",
    price: 89000,
    shipping_fee: 0,
    mattress_price: 79000,
    delivery_days_min: 1,
    delivery_days_max: 2,
    width_cm: 111,
    length_cm: 201,
    height_cm: 30,
    material: "스틸",
    storage_type: "legs_open",
    under_bed_clearance_cm: 30,
    colors: ["블랙", "화이트"],
    storage_capacity: "small",
    dust_blocking: "low",
    cleaning_ease: "easy",
    robot_vacuum_fit: "ok",
    carry_difficulty: "easy",
    self_assembly: "easy",
    assembly_tools: "조립 공구 동봉",
    disassembly_ease: "easy",
    review_risks: ["squeak", "finish_poor"],
    recommended_for: "예산이 빠듯하고 이번 주 안에 받아야 하는 사람",
    not_recommended_for: "삐걱임 소음에 민감한 사람",
    data_confidence: "estimated",
    source_note: "판매페이지+리뷰 취합",
    last_verified_at: "2026-07-06",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000005",
    name: "네스트 원목 서랍침대 슈퍼싱글",
    seller_name: "리바트몰",
    seller_url: "https://example.com/nest-drawer",
    price: 349000,
    shipping_fee: 40000,
    installation_service: "paid",
    installation_fee: 30000,
    mattress_price: 150000,
    delivery_days_min: 7,
    delivery_days_max: 14,
    scheduled_delivery: true,
    width_cm: 117,
    length_cm: 207,
    height_cm: 35,
    material: "오크 원목",
    storage_type: "drawer",
    has_headboard: true,
    colors: ["월넛", "오크"],
    storage_capacity: "medium",
    dust_blocking: "high",
    cleaning_ease: "easy",
    robot_vacuum_fit: "no",
    carry_difficulty: "hard",
    carry_service_available: true,
    self_assembly: "hard",
    assembly_service_available: true,
    assembly_people: 2,
    assembly_tools: "설치 서비스 이용 권장",
    review_risks: ["drawer_awkward"],
    recommended_for: "마감 품질을 중시하고 오래 쓸 사람",
    not_recommended_for: "예산이 20만원 이하인 사람",
    source_note: "공식몰 상세페이지",
    last_verified_at: "2026-07-01",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000006",
    name: "모던 헤드리스 평상형 침대",
    seller_name: "모던하우스",
    seller_url: "https://example.com/modern-platform",
    price: 119000,
    shipping_fee: 30000,
    mattress_price: 85000,
    delivery_days_min: 10,
    delivery_days_max: 14,
    width_cm: 113,
    length_cm: 204,
    height_cm: 25,
    material: "PB+LPM",
    storage_type: "closed_base",
    colors: ["화이트", "그레이"],
    storage_capacity: "none",
    dust_blocking: "high",
    cleaning_ease: "medium",
    robot_vacuum_fit: "no",
    carry_difficulty: "hard",
    self_assembly: "medium",
    assembly_people: 2,
    assembly_tools: "십자드라이버 필요(미동봉)",
    review_risks: ["delivery_delay"],
    recommended_for: "침대 밑 먼지가 아예 안 쌓이길 원하는 사람",
    not_recommended_for: "엘리베이터 없이 혼자 운반해야 하는 사람",
    data_confidence: "estimated",
    source_note: "판매페이지",
    last_verified_at: "2026-06-28",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000007",
    name: "아르떼 호텔식 헤드보드 침대",
    seller_name: "G마켓",
    seller_url: "https://example.com/arte-hotel",
    price: 199000,
    shipping_fee: 0,
    installation_service: "paid",
    installation_fee: 40000,
    mattress_price: 110000,
    delivery_days_min: 7,
    delivery_days_max: 10,
    width_cm: 116,
    length_cm: 206,
    height_cm: 105,
    material: "PB+패브릭 헤드",
    storage_type: "legs_open",
    under_bed_clearance_cm: 12,
    has_outlet: true,
    has_headboard: true,
    colors: ["베이지", "차콜"],
    storage_capacity: "small",
    dust_blocking: "medium",
    cleaning_ease: "medium",
    robot_vacuum_fit: "check_height",
    carry_difficulty: "medium",
    carry_service_available: true,
    self_assembly: "medium",
    assembly_service_available: true,
    assembly_people: 2,
    assembly_tools: "전동드릴 권장",
    review_risks: ["manual_poor"],
    recommended_for: "헤드 콘센트와 호텔 무드가 필요한 사람",
    not_recommended_for: "하부가 높은 로봇청소기를 쓰는 사람",
    source_note: "판매페이지",
    last_verified_at: "2026-07-07",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000008",
    name: "밀로 리프트업 침대 + 매트리스 세트",
    seller_name: "오늘의집",
    seller_url: "https://example.com/milo-set",
    price: 279000,
    shipping_fee: 0,
    installation_service: "included",
    mattress_included: true,
    mattress_price: null,
    delivery_days_min: 14,
    delivery_days_max: 30,
    width_cm: 119,
    length_cm: 209,
    height_cm: 40,
    material: "PB+본넬 매트리스",
    storage_type: "lift_up",
    colors: ["아이보리"],
    storage_capacity: "large",
    dust_blocking: "high",
    cleaning_ease: "easy",
    robot_vacuum_fit: "no",
    carry_difficulty: "hard",
    carry_service_available: true,
    self_assembly: "not_possible",
    assembly_service_available: true,
    assembly_people: 2,
    assembly_tools: "전문 기사 설치",
    disassembly_ease: "hard",
    review_risks: ["smell", "delivery_delay"],
    recommended_for: "매트리스까지 한 번에 해결하고 싶은 사람",
    not_recommended_for: "2주 안에 받아야 하는 사람",
    data_confidence: "estimated",
    source_note: "판매페이지+리뷰 취합",
    last_verified_at: "2026-07-03",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000009",
    name: "데일리 철제 2단 수납침대",
    seller_name: "11번가",
    seller_url: "https://example.com/daily-steel-drawer",
    price: 139000,
    shipping_fee: 20000,
    mattress_price: 75000,
    delivery_days_min: 5,
    delivery_days_max: 7,
    width_cm: 110,
    length_cm: 200,
    height_cm: 45,
    material: "스틸+PB",
    storage_type: "drawer",
    colors: ["블랙"],
    storage_capacity: "medium",
    dust_blocking: "medium",
    cleaning_ease: "medium",
    robot_vacuum_fit: "no",
    carry_difficulty: "medium",
    self_assembly: "hard",
    assembly_people: 2,
    assembly_tools: "부품 많음·전동드릴 권장",
    disassembly_ease: "easy",
    review_risks: ["squeak", "missing_parts", "assembly_hard"],
    recommended_for: "가성비 수납침대가 필요하고 공구를 다룰 수 있는 사람",
    not_recommended_for: "조립 경험이 없는 사람",
    data_confidence: "estimated",
    source_note: "판매페이지+리뷰 취합",
    last_verified_at: "2026-06-30",
  },
  {
    ...base,
    id: "00000000-0000-4000-8000-000000000010",
    name: "그로브 소나무 원목 침대 (주문제작)",
    seller_name: "그로브 스마트스토어",
    seller_url: "https://example.com/grove-pine",
    price: 169000,
    shipping_fee: 35000,
    mattress_price: 100000,
    delivery_days_min: 21,
    delivery_days_max: 30,
    scheduled_delivery: true,
    width_cm: 114,
    length_cm: 204,
    height_cm: 30,
    material: "소나무 원목",
    storage_type: "legs_open",
    under_bed_clearance_cm: 18,
    colors: ["내추럴", "브라운"],
    storage_capacity: "small",
    dust_blocking: "low",
    cleaning_ease: "easy",
    robot_vacuum_fit: "check_height",
    carry_difficulty: "medium",
    self_assembly: "easy",
    assembly_tools: "육각렌치 동봉",
    disassembly_ease: "easy",
    review_risks: ["extra_cost"],
    recommended_for: "원목 질감과 이사할 때 분해 편의를 중시하는 사람",
    not_recommended_for: "2주 안에 받아야 하는 사람",
    source_note: "공식 스마트스토어",
    last_verified_at: "2026-07-04",
  },
];
