-- Intentionally empty.
--
-- Example products live only in src/lib/seed-data.ts for DATA_MODE=demo and
-- automated tests. A live Supabase catalog must be loaded and published with
-- the catalog:validate, catalog:import, and catalog:release commands.
